export default function PrivacyPolicyPage() {
  return (
    <div className="bg-brand-black min-h-screen pt-32 pb-24">
      <div className="default-container max-w-3xl">
        <h1 className="font-bebas text-[56px] text-brand-white uppercase leading-none tracking-tight mb-8">Privacy Policy</h1>
        
        <div className="font-inter text-[15px] text-brand-muted leading-relaxed flex flex-col gap-6">
          <p>
            Highgrand ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy clarifies how we collect, use, and safeguard your business and personal information when you use our wholesale platform at highgrand.in.
          </p>
          
          <h2 className="font-bebas text-[32px] text-brand-white uppercase mt-8 border-b border-brand-border pb-4">Information We Collect</h2>
          <p>
            When you register for a reseller account, we collect the necessary information required to facilitate our B2B operations. This includes your business name, representative name, email address, WhatsApp/phone number, GSTIN (optional), and logistics addressing details. We also securely harvest encrypted session data generated by NextAuth for authentication purposes.
          </p>

          <h2 className="font-bebas text-[32px] text-brand-white uppercase mt-8 border-b border-brand-border pb-4">How We Use Your Data</h2>
          <ul className="list-disc pl-5 mt-2 space-y-2 text-brand-muted">
            <li><strong>Account Verification:</strong> To evaluate and approve your reseller application.</li>
            <li><strong>Communication:</strong> To send bulk quotes, dispatch updates, and respond to your queries via email or our official WhatsApp channels.</li>
            <li><strong>Invoicing:</strong> To generate legally compliant tax invoices matching your provided business credentials.</li>
            <li><strong>Platform Security:</strong> To protect against unauthorised access to our wholesale catalog.</li>
          </ul>

          <h2 className="font-bebas text-[32px] text-brand-white uppercase mt-8 border-b border-brand-border pb-4">Data Sharing</h2>
          <p>
            We do not sell, trade, or rent your business information to third parties. We only share necessary data with trusted third-party service providers directly tied to our operations (e.g., logistics partners like Delhivery or Xpressbees to deliver your bulk stock, or our hosting providers like Vercel).
          </p>

          <h2 className="font-bebas text-[32px] text-brand-white uppercase mt-8 border-b border-brand-border pb-4">Security Infrastructure</h2>
          <p>
            Highgrand employs modern, industry-standard cryptographic techniques to secure our database. Passwords are mathematically hashed using bcrypt, and user sessions are managed securely via tamper-proof JWT tokens. While we invest heavily in security, please understand that no method of electronic transmission is 100% impenetrable.
          </p>

          <p className="mt-8 text-[12px] uppercase tracking-widest border-t border-brand-border pt-6">Last Updated: April 2026</p>
        </div>
      </div>
    </div>
  )
}
